### ISSUE TITLE
Does not support colored nametags (teams)

### ISSUE THREAD

**Issue by NurdTurd** [garrettjoecox/scriptserver#1]
I tried using `scriptserver-essentials` but I found out it doesn't work with players who have colored nametags when in a team.

![](https://shel.io/f/bW7.png)

**Comment by garrettjoecox** [comment]
Interesting,

Although this seems to be an issue with scriptserver-essentials would you mind moving the issue over there?

**Comment by NurdTurd** [comment]
No problem.
