### ISSUE TITLE
clone-able server example.

### ISSUE THREAD

**Issue by jschiarizzi** [garrettjoecox/scriptserver#11]
Very cool project. I tried spinning up an instance using glitch.com but couldn't quite get it. Maybe we could get one running there that people can easily remix?

**Comment by garrettjoecox** [comment]
Hmm, I'm not sure glitch.com is the best way to try this out, it doesn't seem to be supported after browsing their forums, and I was unable to get even just a bare server running (without scriptserver) without it crashing from lack of memory.

**Comment by garrettjoecox** [comment]
Just an update, back when I refactored and updated all of the modules to 1.0.0, I accidentally published them to my employers private NPM registry, and just found out about this today x_x

This has been resolved and all module updates have been published to NPM, this could be the origin of your issue. I'm going to close this for now, if you have any further questions let me know.

**Comment by jschiarizzi** [comment]
Interesting... I will check it out soon, probably won't get to it this weekend. 🐰
