### ISSUE TITLE
server.send not functioning

### ISSUE THREAD

**Issue by RowanHall** [garrettjoecox/scriptserver#12]
Server.send('*command*') not functioning.

there's no more to say here, it just isn't doing anything.

**Comment by etienneorlhac** [comment]
Same issue here, this seems to be a problem with Rcon.

While waiting for a fix, another way to send commands is to send them directly to the input stream of the server process :

```js
// Instead of 
server.send("say hi");
// Use this
server.spawn.stdin.write("/say hi\n");
```

Notice the slash at the beginning and the newline character that are needed for the server to recognize the command.

**Comment by etienneorlhac** [comment]
I found what was at fault for me. Make sure that the server is setup correctly to allow RCON.
For example, if you were to create your server object like so
```js
const server = new ScriptServer({
    core: {
        jar: "server.jar",
        args: [
            "-Xmx2G"
        ],
        rcon: {
            port: "25575",
            password: "0000"
        }
    }
});
```
Then the server's `server.properties` file needs to have these lines
```ini
enable-rcon=true
rcon.port=25575
rcon.password=0000
```
It seems that newer versions of the server jar (in my case the latest snapshot) don't automatically generate those lines.

**Comment by RowanHall** [comment]
Thanks!

**Comment by garrettjoecox** [comment]
Sorry for the trouble! I seem to have completely forgot to document the requirement to enable RCON in your server.properties. I will leave this ticket open until I am able to do so.
