### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SecretsMan** [garrettjoecox/scriptserver#14]
Hello !
I have a question, I would like to create a minecraft server without the mechanics of mc (by reimplementing some features of Minecraft)

Do you think this is possible via your library

**Comment by garrettjoecox** [comment]
Hey there,
I'm not sure I fully understand what you mean. Perhaps you could provide an example of what you are trying to do?

**Comment by garrettjoecox** [comment]
Going to go ahead and close this, as it doesn't appear to be an issue with the repository. Feel free to email me the details of your question - garrettjcox@gmail.com
