### ISSUE TITLE
Minecraft server files in subfolder

### ISSUE THREAD

**Issue by fjeddy** [garrettjoecox/scriptserver#15]
Hello,

Brilliant idea. Tho, if I use this, then it sets up all the server files in the root of the directory, with node_modules, server.js / index.js and so on. This quickly becomes a huge mess.

Is there any way to have the minecraft server specific files install in a subfolder?

**Comment by fjeddy** [comment]
Yes it is,

```
spawnOpts: {
  cwd: 'path/to/install/in'
}
```

will let you define exactly where the server is installed, tho it seems to require a full path and not a relative path.

**Comment by garrettjoecox** [comment]
Hey there, glad you were able to figure that out, I'll make a note to add that configuration to the documentation, and to support relative paths as well.
