### ISSUE TITLE
RCON messages don't support UTF-8

### ISSUE THREAD

**Issue by fjeddy** [garrettjoecox/scriptserver#18]
Seems like having ÆØÅ in `send` and `tellRaw` commands just return ? in-game. ÆØÅ is not working in the command themselves either.

Been looking for a few hours now, I can't seem to figure out where exactly the encoding problem occur. Doing a tellraw outside the library, directly in the games console, works fine, so i'm pretty sure it's a problem in the code.

Got any idea?

**Comment by garrettjoecox** [comment]
Hmm, this seems to be a limitation of the RCON module in use `simple-rcon`. It's encoding the RCON packets in `ascii`, the characters you are trying to use are `utf8`.

I will submit an issue on that repository, after a quick attempt changing the encoding to `utf8` doesn't cause any issues but I'll need to do some more testing this weekend.
