### ISSUE TITLE
This repo is awesome! I love it very much, so I create the "onload" module for this.

### ISSUE THREAD

**Issue by kyob1010** [garrettjoecox/scriptserver#2]
This is the repo for scriptserver-onload.
https://github.com/kyob1010/scriptserver-onload

**Comment by garrettjoecox** [comment]
Great, if you have published on NPM I'll add it to the README

**Comment by kyob1010** [comment]
Yes, I have already published it.
I notice that you have "scriptserver-event", and maybe it can just simply add on with it.

**Comment by garrettjoecox** [comment]
That's not a bad idea. Have at it!
