### ISSUE TITLE
Feature Request: Add directory option in core

### ISSUE THREAD

**Issue by EnDylan** [garrettjoecox/scriptserver#22]
I would like to request a feature that allows the server to be run in a directory.
For example:
```
const server = new ScriptServer({
    core: {
        jar: serverJar,
        args: ['-Xmx10G'],
        dir: './minecraft/'
    }
});
```
and it would output all the server files in that directory.

**Comment by garrettjoecox** [comment]
Hey there,

I haven't tested this, but it should be possible via passing in a directory in the `core.spawnOpts.cwd`. I will test this when I get home, and then close the issue if I don't run into problems.

**Comment by EnDylan** [comment]
How do I do that?
Could you provide a code example?
Thanks!

**Comment by ImBaedin** [comment]
I believe he means

```
const server = new ScriptServer({
    core: {
        jar: serverJar,
        args: ['-Xmx10G'],
        dir: './minecraft/'
        spawnOpts: {
             cwd: 'directory/path/here'
        }
    }
});
```

**Comment by garrettjoecox** [comment]
@ImBaedin yep, thanks.

@EnDylan Just tried this out and it works fine. Let me know if you run into any further issues.
