### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Buggitt** [garrettjoecox/scriptserver#25]
Sat down to play with this today but can't seem to get the core to start.
Using the basic example and get this error:

```
$ node ServerScript.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by EnDylan** [comment]
Please provide your source code as it would probably be easier & faster for one to help you with this.

**Comment by Buggitt** [comment]
All I’m trying to do is use the example code.

‘’’
const ScriptServer = require('scriptserver');

const server = new ScriptServer({
  core: {
    jar: 'minecraft_server.jar',
    args: ['-Xmx2G'],
    rcon: {
      port: '25575',
      password: 'password'
    }
  }
});

server.start();
‘’’

Which is in my “ServerScript.js” which I’m running.

**Comment by ImBaedin** [comment]
And you have the server jar in the same directory as your server?

**Comment by Buggitt** [comment]
@ImBaedin
Yep, they are in the same directory.
I downloaded a vanilla 1.12.2 server jar and started it on its own (to generate the Eula file and server.properties) added the necessary lines to the server properties.
And standalone the Minecraft server runs fine.
