### ISSUE TITLE
Unable to install via npm

### ISSUE THREAD

**Issue by kellofkindles** [garrettjoecox/scriptserver#29]
Whenever I use the command `npm i scriptserver` I get this error:
```
7 error enoent Error while executing:
37 error enoent undefined ls-remote -h -t ssh://git@github.com/garrettjoecox/simple-rcon.git
37 error enoent
37 error enoent
37 error enoent spawn git ENOENT
38 error enoent This is related to npm not being able to find a file.
```
Edit: It seems to have to do with the lodash.defaultsdeep module.

[Full log - 2020-05-02T20_11_07_836Z-debug.log](https://github.com/garrettjoecox/scriptserver/files/4568696/2020-05-02T20_11_07_836Z-debug.log)

**Comment by garrettjoecox** [comment]
@kellofkindles Was this resolved? I was not able to reproduce

**Comment by garrettjoecox** [comment]
It seems it failed when NPM tried to clone my fork of simple-rcon, `git` not defined, did you have git installed?

**Comment by kellofkindles** [comment]
I did try to install git afterwards, however that did not seem to solve the issue. I instead used a different machine (Windows 10, with git) and that worked.
