### ISSUE TITLE
Problem for "index.js: line=19"

### ISSUE THREAD

**Issue by kyob1010** [garrettjoecox/scriptserver#3]
I want to make an auto-restart server, but the code in "index.js: line=19" ends the server when minecraft server close.

I think that it can have a setting which notice me when minecraft server close instead of close entire server. 

b.t.w I send a pull request to the repo "scriptserver-event"

**Comment by garrettjoecox** [comment]
This will be addressed soon, as I'm working on something similar. 

The interface will be something like
```
var server = new ScriptServer({ config });

server.start('jar', ['args']);

server.stop();
```

**Comment by garrettjoecox** [comment]
Pushed an update to resolve this
