### ISSUE TITLE
"npm install scriptserver" error. NPM not finding the module to install

### ISSUE THREAD

**Issue by dsync44** [garrettjoecox/scriptserver#34]
Hey guys!

Trying to use this module, but can't install it trought npm install command.
This is what I get when I try to install using `npm install scriptserver`

````
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "scriptserver" under a package
npm ERR! also called "scriptserver". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
````

The complete log is attached here.
Thanks!

[2020-12-15T15_04_45_806Z-debug.log](https://github.com/garrettjoecox/scriptserver/files/5696735/2020-12-15T15_04_45_806Z-debug.log)

**Comment by Kehino** [comment]
Hello dsync44,

In which folder are you trying to install the module? Don't install it as global, but rather in your working directory (which will contain the .jar Minecraft server). As you can see in the log, there may be a conflict in the folder name.

**Comment by garrettjoecox** [comment]
This will happen when your project `name` in your local `package.json` is `scriptserver`, try changing it to `server` or something and give it another try
