### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by matvejs16** [garrettjoecox/scriptserver#55]
Hey, is it still maintained and working on latest minecraft versions?

**Comment by garrettjoecox** [comment]
Hey there, there isn't super active development on it, but I usually will verify it works and update anything that needs it about once a year, with the last updates being verified for 1.20 IIRC.

As stated in the readme though:
> Technically, it can work with any version of Minecraft that logs to STDOUT and has an RCON port exposed (Which dates back to ~2012 in Vanilla). Where problems usually arise from version to version is logging format changes, but it mostly just requires fiddling with the RegExp set up in the indiviual plugins.

So with some elbow grease you can get it working on your own with any version 👍
