### ISSUE TITLE
A bug for start and stop function

### ISSUE THREAD

**Issue by kyob1010** [garrettjoecox/scriptserver#6]
When you stop a running server, it will kill the child process and set the variable to null which also known as "server.spawn".

Later, I exit my program.
It means that it will trigger the callback of event process.exit.
Here is where the bug happened.

"server.spawn === null"
AND
the callback calls "server.spawn.kill" function

I'll do a quick fix for that.

**Comment by kyob1010** [comment]
I send a pull request for my solution.

**Comment by garrettjoecox** [comment]
Merged the PR, thanks!
